//! # DBus interface proxy for: `org.freedesktop.NetworkManager.Checkpoint`
//!
//! This code was generated by `zbus-xmlgen` `3.1.1` from DBus introspection data.
//! Source: `org.freedesktop.NetworkManager.Checkpoint.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!

use zbus::dbus_proxy;

#[dbus_proxy(
    interface = "org.freedesktop.NetworkManager.Checkpoint",
    assume_defaults = true
)]
pub trait Checkpoint {
    /// Created property
    #[dbus_proxy(property)]
    fn created(&self) -> zbus::Result<i64>;

    /// Devices property
    #[dbus_proxy(property)]
    fn devices(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// RollbackTimeout property
    #[dbus_proxy(property)]
    fn rollback_timeout(&self) -> zbus::Result<u32>;
}
