#![allow(warnings, rust_2018_idioms)]
mod nm;
mod nm_accesspoint;
mod nm_agentmanager;
mod nm_checkpoint;
mod nm_connection_active;
mod nm_device;
mod nm_device_adsl;
mod nm_device_bluetooth;
mod nm_device_bond;
mod nm_device_bridge;
mod nm_device_dummy;
mod nm_device_generic;
mod nm_device_infiniband;
mod nm_device_iptunnel;
mod nm_device_loopback;
mod nm_device_lowpan;
mod nm_device_macsec;
mod nm_device_macvlan;
mod nm_device_modem;
mod nm_device_olpcmesh;
mod nm_device_ovsbridge;
mod nm_device_ovsinterface;
mod nm_device_ovsport;
mod nm_device_ppp;
mod nm_device_statistics;
mod nm_device_team;
mod nm_device_tun;
mod nm_device_veth;
mod nm_device_vlan;
mod nm_device_vrf;
mod nm_device_vxlan;
mod nm_device_wifip2p;
mod nm_device_wimax;
mod nm_device_wired;
mod nm_device_wireguard;
mod nm_device_wireless;
mod nm_device_wpan;
mod nm_dhcp4config;
mod nm_dhcp6config;
mod nm_dnsmanager;
mod nm_ip4config;
mod nm_ip6config;
mod nm_ppp;
mod nm_secretagent;
mod nm_settings;
mod nm_settings_connection;
mod nm_vpn_connection;
mod nm_vpn_plugin;
mod nm_wifip2ppeer;
mod nm_wimax_nsp;

pub(super) use nm::{NetworkManagerProxy, NetworkManagerProxyBlocking};
pub(super) use nm_accesspoint::{AccessPointProxy, AccessPointProxyBlocking};
pub(super) use nm_agentmanager::{AgentManagerProxy, AgentManagerProxyBlocking};
pub(super) use nm_checkpoint::{CheckpointProxy, CheckpointProxyBlocking};
pub(super) use nm_connection_active::{ConnectionActiveProxy, ConnectionActiveProxyBlocking};
pub(super) use nm_device::{DeviceProxy, DeviceProxyBlocking};
pub(super) use nm_device_adsl::{DeviceAdslProxy, DeviceAdslProxyBlocking};
pub(super) use nm_device_bluetooth::{DeviceBluetoothProxy, DeviceBluetoothProxyBlocking};
pub(super) use nm_device_bond::{DeviceBondProxy, DeviceBondProxyBlocking};
pub(super) use nm_device_bridge::{DeviceBridgeProxy, DeviceBridgeProxyBlocking};
pub(super) use nm_device_dummy::{DeviceDummyProxy, DeviceDummyProxyBlocking};
pub(super) use nm_device_generic::{DeviceGenericProxy, DeviceGenericProxyBlocking};
pub(super) use nm_device_infiniband::{DeviceInfinibandProxy, DeviceInfinibandProxyBlocking};
pub(super) use nm_device_iptunnel::{DeviceIPTunnelProxy, DeviceIPTunnelProxyBlocking};
pub(super) use nm_device_loopback::{DeviceLoopbackProxy, DeviceLoopbackProxyBlocking};
pub(super) use nm_device_lowpan::{DeviceLowpanProxy, DeviceLowpanProxyBlocking};
pub(super) use nm_device_macsec::{DeviceMacsecProxy, DeviceMacsecProxyBlocking};
pub(super) use nm_device_macvlan::{DeviceMacvlanProxy, DeviceMacvlanProxyBlocking};
pub(super) use nm_device_modem::{DeviceModemProxy, DeviceModemProxyBlocking};
pub(super) use nm_device_olpcmesh::{DeviceOlpcMeshProxy, DeviceOlpcMeshProxyBlocking};
pub(super) use nm_device_ovsbridge::{DeviceOvsBridgeProxy, DeviceOvsBridgeProxyBlocking};
pub(super) use nm_device_ovsinterface::{DeviceOvsInterfaceProxy, DeviceOvsInterfaceProxyBlocking};
pub(super) use nm_device_ovsport::{DeviceOvsPortProxy, DeviceOvsPortProxyBlocking};
pub(super) use nm_device_ppp::{DevicePppProxy, DevicePppProxyBlocking};
pub(super) use nm_device_statistics::{DeviceStatisticsProxy, DeviceStatisticsProxyBlocking};
pub(super) use nm_device_team::{DeviceTeamProxy, DeviceTeamProxyBlocking};
pub(super) use nm_device_tun::{DeviceTunProxy, DeviceTunProxyBlocking};
pub(super) use nm_device_veth::{DeviceVethProxy, DeviceVethProxyBlocking};
pub(super) use nm_device_vlan::{DeviceVlanProxy, DeviceVlanProxyBlocking};
pub(super) use nm_device_vrf::{DeviceVrfProxy, DeviceVrfProxyBlocking};
pub(super) use nm_device_vxlan::{DeviceVxlanProxy, DeviceVxlanProxyBlocking};
pub(super) use nm_device_wifip2p::{DeviceWifiP2PProxy, DeviceWifiP2PProxyBlocking};
pub(super) use nm_device_wimax::{DeviceWiMaxProxy, DeviceWiMaxProxyBlocking};
pub(super) use nm_device_wired::{DeviceWiredProxy, DeviceWiredProxyBlocking};
pub(super) use nm_device_wireguard::{DeviceWireGuardProxy, DeviceWireGuardProxyBlocking};
pub(super) use nm_device_wireless::{DeviceWirelessProxy, DeviceWirelessProxyBlocking};
pub(super) use nm_device_wpan::{DeviceWpanProxy, DeviceWpanProxyBlocking};
pub(super) use nm_dhcp4config::{DHCP4ConfigProxy, DHCP4ConfigProxyBlocking};
pub(super) use nm_dhcp6config::{DHCP6ConfigProxy, DHCP6ConfigProxyBlocking};
pub(super) use nm_dnsmanager::{DnsManagerProxy, DnsManagerProxyBlocking};
pub(super) use nm_ip4config::{IP4ConfigProxy, IP4ConfigProxyBlocking};
pub(super) use nm_ip6config::{IP6ConfigProxy, IP6ConfigProxyBlocking};
pub(super) use nm_ppp::{PPPProxy, PPPProxyBlocking};
pub(super) use nm_secretagent::{SecretAgentProxy, SecretAgentProxyBlocking};
pub(super) use nm_settings::{SettingsProxy, SettingsProxyBlocking};
pub(super) use nm_settings_connection::{SettingsConnectionProxy, SettingsConnectionProxyBlocking};
pub(super) use nm_vpn_connection::{VPNConnectionProxy, VPNConnectionProxyBlocking};
pub(super) use nm_vpn_plugin::{VPNPluginProxy, VPNPluginProxyBlocking};
pub(super) use nm_wifip2ppeer::{WifiP2PPeerProxy, WifiP2PPeerProxyBlocking};
pub(super) use nm_wimax_nsp::{WiMaxNspProxy, WiMaxNspProxyBlocking};
