//! # DBus interface proxy for: `org.freedesktop.NetworkManager.Device.Macvlan`
//!
//! This code was generated by `zbus-xmlgen` `3.1.1` from DBus introspection data.
//! Source: `org.freedesktop.NetworkManager.Device.Macvlan.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!

use zbus::dbus_proxy;

#[dbus_proxy(
    interface = "org.freedesktop.NetworkManager.Device.Macvlan",
    assume_defaults = true
)]
pub trait DeviceMacvlan {
    /// Mode property
    #[dbus_proxy(property)]
    fn mode(&self) -> zbus::Result<String>;

    /// NoPromisc property
    #[dbus_proxy(property)]
    fn no_promisc(&self) -> zbus::Result<bool>;

    /// Parent property
    #[dbus_proxy(property)]
    fn parent(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Tap property
    #[dbus_proxy(property)]
    fn tap(&self) -> zbus::Result<bool>;
}
