//! # DBus interface proxy for: `org.freedesktop.NetworkManager.Device.Statistics`
//!
//! This code was generated by `zbus-xmlgen` `3.1.1` from DBus introspection data.
//! Source: `org.freedesktop.NetworkManager.Device.Statistics.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!

use zbus::dbus_proxy;

#[dbus_proxy(
    interface = "org.freedesktop.NetworkManager.Device.Statistics",
    assume_defaults = true
)]
pub trait DeviceStatistics {
    /// RefreshRateMs property
    #[dbus_proxy(property)]
    fn refresh_rate_ms(&self) -> zbus::Result<u32>;
    fn set_refresh_rate_ms(&self, value: u32) -> zbus::Result<()>;

    /// RxBytes property
    #[dbus_proxy(property)]
    fn rx_bytes(&self) -> zbus::Result<u64>;

    /// TxBytes property
    #[dbus_proxy(property)]
    fn tx_bytes(&self) -> zbus::Result<u64>;
}
