//! # DBus interface proxy for: `org.freedesktop.NetworkManager.VPN.Connection`
//!
//! This code was generated by `zbus-xmlgen` `3.1.1` from DBus introspection data.
//! Source: `org.freedesktop.NetworkManager.VPN.Connection.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!

use zbus::dbus_proxy;

#[dbus_proxy(
    interface = "org.freedesktop.NetworkManager.VPN.Connection",
    assume_defaults = true
)]
pub trait VPNConnection {
    /// VpnStateChanged signal
    #[dbus_proxy(signal)]
    fn vpn_state_changed(&self, state: u32, reason: u32) -> zbus::Result<()>;

    /// Banner property
    #[dbus_proxy(property)]
    fn banner(&self) -> zbus::Result<String>;

    /// VpnState property
    #[dbus_proxy(property)]
    fn vpn_state(&self) -> zbus::Result<u32>;
}
