//! # DBus interface proxy for: `org.freedesktop.NetworkManager.Device.Macsec`
//!
//! This code was generated by `zbus-xmlgen` `3.1.1` from DBus introspection data.
//! Source: `org.freedesktop.NetworkManager.Device.Macsec.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!

use zbus::dbus_proxy;

#[dbus_proxy(
    interface = "org.freedesktop.NetworkManager.Device.Macsec",
    assume_defaults = true
)]
pub trait DeviceMacsec {
    /// CipherSuite property
    #[dbus_proxy(property)]
    fn cipher_suite(&self) -> zbus::Result<u64>;

    /// EncodingSa property
    #[dbus_proxy(property)]
    fn encoding_sa(&self) -> zbus::Result<u8>;

    /// Encrypt property
    #[dbus_proxy(property)]
    fn encrypt(&self) -> zbus::Result<bool>;

    /// Es property
    #[dbus_proxy(property)]
    fn es(&self) -> zbus::Result<bool>;

    /// IcvLength property
    #[dbus_proxy(property)]
    fn icv_length(&self) -> zbus::Result<u8>;

    /// IncludeSci property
    #[dbus_proxy(property)]
    fn include_sci(&self) -> zbus::Result<bool>;

    /// Parent property
    #[dbus_proxy(property)]
    fn parent(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Protect property
    #[dbus_proxy(property)]
    fn protect(&self) -> zbus::Result<bool>;

    /// ReplayProtect property
    #[dbus_proxy(property)]
    fn replay_protect(&self) -> zbus::Result<bool>;

    /// Scb property
    #[dbus_proxy(property)]
    fn scb(&self) -> zbus::Result<bool>;

    /// Sci property
    #[dbus_proxy(property)]
    fn sci(&self) -> zbus::Result<u64>;

    /// Validation property
    #[dbus_proxy(property)]
    fn validation(&self) -> zbus::Result<String>;

    /// Window property
    #[dbus_proxy(property)]
    fn window(&self) -> zbus::Result<u32>;
}
