//! # DBus interface proxy for: `org.freedesktop.NetworkManager.Device.WiMax`
//!
//! This code was generated by `zbus-xmlgen` `3.1.1` from DBus introspection data.
//! Source: `org.freedesktop.NetworkManager.Device.WiMax.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!

use zbus_macros::proxy;

#[proxy(
    interface = "org.freedesktop.NetworkManager.Device.WiMax",
    assume_defaults = true
)]
pub trait DeviceWiMax {
    /// GetNspList method
    fn get_nsp_list(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// NspAdded signal
    #[zbus(signal)]
    fn nsp_added(&self, nsp: zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// NspRemoved signal
    #[zbus(signal)]
    fn nsp_removed(&self, nsp: zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// ActiveNsp property
    #[zbus(property)]
    fn active_nsp(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Bsid property
    #[zbus(property)]
    fn bsid(&self) -> zbus::Result<String>;

    /// CenterFrequency property
    #[zbus(property)]
    fn center_frequency(&self) -> zbus::Result<u32>;

    /// Cinr property
    #[zbus(property)]
    fn cinr(&self) -> zbus::Result<i32>;

    /// HwAddress property
    #[zbus(property)]
    fn hw_address(&self) -> zbus::Result<String>;

    /// Nsps property
    #[zbus(property)]
    fn nsps(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// Rssi property
    #[zbus(property)]
    fn rssi(&self) -> zbus::Result<i32>;

    /// TxPower property
    #[zbus(property)]
    fn tx_power(&self) -> zbus::Result<i32>;
}
