//! # DBus interface proxy for: `org.freedesktop.NetworkManager.Device.Veth`
//!
//! This code was generated by `zbus-xmlgen` `3.1.1` from DBus introspection data.
//! Source: `org.freedesktop.NetworkManager.Device.Veth.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!

use zbus_macros::proxy;

#[proxy(
    interface = "org.freedesktop.NetworkManager.Device.Veth",
    assume_defaults = true
)]
pub trait DeviceVeth {
    /// Peer property
    #[zbus(property)]
    fn peer(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;
}
